(()=>{'use strict';
const C=window.MCL_SUPABASE||{};
const sb=window.supabase.createClient(C.url,C.publishableKey,{auth:{persistSession:true,autoRefreshToken:true}});
const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID();
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function modal(title,html){const x=document.createElement('div');x.className='modal-backdrop';x.innerHTML=`<section class="modal" style="width:min(900px,96vw)"><div class="modal-head"><h3>${E(title)}</h3><button class="btn ghost small" data-x>Fechar</button></div>${html}</section>`;document.body.append(x);q('[data-x]',x).onclick=()=>x.remove();return x}
function currentMonth(){return q('#content input[type="month"]')?.value||new Date().toISOString().slice(0,7)}
async function natures(selected=''){const {data}=await sb.from('financeiro_naturezas').select('nome,ativo').order('nome');const a=(data||[]).filter(x=>x.ativo!==false).map(x=>x.nome).filter(Boolean);if(selected&&!a.includes(selected))a.unshift(selected);return a}
async function rowForm(direction='Entrada',id=null){let row=null;if(id){const r=await sb.from('financeiro_fluxo').select('*').eq('id',id).maybeSingle();if(r.error)return alert(r.error.message);row=r.data}const ns=await natures(row?.natureza||''),dir=row?.direcao||direction,x=modal(row?'Editar lançamento':`Nova ${dir.toLowerCase()}`,`<form id="mclFlowForm"><div class="modal-body"><div class="form-grid"><div class="field"><label>Data</label><input name="date" type="date" value="${E(String(row?.data_movimento||`${currentMonth()}-01`).slice(0,10))}" required></div><div class="field"><label>Tipo</label><select name="direction"><option ${dir==='Entrada'?'selected':''}>Entrada</option><option ${dir==='Saída'?'selected':''}>Saída</option></select></div><div class="field full"><label>Descrição</label><input name="description" value="${E(row?.descricao||'')}" required></div><div class="field"><label>Natureza</label><select name="nature">${ns.map(n=>`<option ${n===(row?.natureza||'')?'selected':''}>${E(n)}</option>`).join('')}</select></div><div class="field"><label>Valor</label><input name="value" type="number" min="0.01" step="0.01" value="${row?.valor??''}" required></div><div class="field full"><label>Origem</label><input value="${E(row?.origem||'Manual')}" readonly></div></div></div><div class="modal-foot">${row?'<button type="button" class="btn danger" id="mclFlowDelete">Excluir</button>':''}<button class="btn">Salvar</button></div></form>`);q('#mclFlowForm',x).onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),value=Math.abs(Number(f.get('value')||0));if(!value)return alert('Informe um valor maior que zero.');const {data:{user}}=await sb.auth.getUser(),payload={data_movimento:f.get('date'),direcao:f.get('direction'),descricao:String(f.get('description')).trim(),natureza:f.get('nature')||null,valor:value,origem:row?.origem||'Manual',referencia_id:row?.referencia_id||null,dados:{...(row?.dados||{}),editado_manualmente:true},created_by:row?.created_by||user?.id||null};const r=row?await sb.from('financeiro_fluxo').update(payload).eq('id',row.id):await sb.from('financeiro_fluxo').insert({id:uid(),...payload});if(r.error)return alert(r.error.message);x.remove();location.reload()};if(row)q('#mclFlowDelete',x).onclick=async()=>{if(!confirm(`Excluir o lançamento “${row.descricao}”?`))return;const r=await sb.from('financeiro_fluxo').delete().eq('id',row.id);if(r.error)return alert(r.error.message);x.remove();location.reload()}}
function parseDate(s){const p=String(s||'').trim().split('/');return p.length===3?`${p[2]}-${p[1]}-${p[0]}`:''}
function parseMoney(s){let v=String(s||'').replace(/R\$/gi,'').replace(/\s/g,'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'');return Math.abs(Number(v)||0)}
async function bindRows(){const tables=qa('#content table');if(!tables.length)return;const {data}=await sb.from('financeiro_fluxo').select('id,data_movimento,descricao,natureza,direcao,valor');const pool=[...(data||[])];for(const tr of qa('#content table tbody tr')){const td=tr.querySelectorAll('td');if(td.length<5||tr.dataset.mclFlowId)continue;const date=parseDate(td[0]?.textContent),desc=(td[1]?.textContent||'').trim(),nature=(td[2]?.textContent||'').trim(),value=parseMoney(td[4]?.textContent),r=pool.find(x=>String(x.data_movimento).slice(0,10)===date&&String(x.descricao||'').trim()===desc&&Math.abs(Number(x.valor||0)-value)<.01);if(!r)continue;tr.dataset.mclFlowId=r.id;tr.draggable=true;tr.style.cursor='grab';if(!tr.querySelector('[data-mcl-edit]')){const cell=document.createElement('td'),b=document.createElement('button');b.className='btn ghost small';b.dataset.mclEdit=r.id;b.textContent='Editar';b.onclick=e=>{e.stopPropagation();rowForm(r.direcao,r.id)};cell.append(b);tr.append(cell)}}
}
function install(){if(!/Administrador/i.test(q('.user-mini')?.textContent||''))return;if((q('#title')?.textContent||'')!=='Fluxo de Caixa')return;const c=q('#content'),bar=q('.toolbar',c);if(!bar)return;let right=q('.right',bar);if(!right){right=document.createElement('div');right.className='right';bar.append(right)}if(!q('#mclAddIn')){const a=document.createElement('button');a.id='mclAddIn';a.className='btn ghost';a.textContent='+ Adicionar entrada';a.onclick=()=>rowForm('Entrada');right.append(a)}if(!q('#mclAddOut')){const a=document.createElement('button');a.id='mclAddOut';a.className='btn';a.textContent='+ Adicionar saída';a.onclick=()=>rowForm('Saída');right.append(a)}bindRows()}
new MutationObserver(()=>setTimeout(install,40)).observe(document.documentElement,{childList:true,subtree:true});setInterval(install,700);
window.MCLCashflowEditor={rowForm,bindRows};
})();