const test=require('node:test');const assert=require('node:assert/strict');const B=require('../budget-tools');
test('preserva realizado e dados anteriores sem mutar o orçamento',()=>{const b={setor:'Obras',realizado:123.45,dados:{outro:'preservar'}};const d=B.detail(b);assert.equal(d.base,123.45);d.etapas.push({});assert.equal(b.dados.mcl_orcamento,undefined);assert.equal(b.dados.outro,'preservar')});
test('quantidade, desconto e centavos',()=>{assert.equal(B.itemTotal({quantidade:3,unitario:0.1,desconto:0.01}),0.29);assert.equal(B.itemTotal({quantidade:2.5,unitario:40,desconto:10}),90)});
test('valores inválidos não passam',()=>{for(const n of [-1,Infinity,'abc',1e13])assert.throws(()=>B.amount(n));assert.throws(()=>B.itemTotal({quantidade:0,unitario:2}));assert.throws(()=>B.itemTotal({quantidade:1,unitario:2,desconto:3}))});
test('realizado anterior e gastos são somados sem perder o legado',()=>{const d={base:100,etapas:[{itens:[{quantidade:2,unitario:50,realizado:20},{quantidade:1,unitario:40,realizado:0}]}]};assert.deepEqual(B.totals(d),{previsto:140,realizado:120,itens:2});d.etapas[0].itens.splice(0,1);assert.deepEqual(B.totals(d),{previsto:40,realizado:100,itens:1})});
test('etapa desconsidera gastos cancelados',()=>{assert.deepEqual(B.stageTotals({itens:[{quantidade:1,unitario:50,realizado:0,status:'Cancelado'},{quantidade:1,unitario:20,realizado:10,status:'Pago'}]}),{previsto:20,realizado:10,itens:1})});
const fs=require('node:fs'),vm=require('node:vm');
function persistence({administrator=true,error=null}={}){const source=fs.readFileSync(require.resolve('../app.js'),'utf8');let filters=[],payload;const chain={eq(k,v){filters.push([k,v]);return this},select(){return this},single:async()=>({data:{id:'b'},error})};const context={BT:B,budgetTotals:B.totals,admin:()=>administrator,profile:{nome:'Administrador de teste'},db:{budgets:[{id:'b'}]},load:async()=>{},Date,Error,sb:{from(){return{update(o){payload=o;return chain}}}}};vm.createContext(context);vm.runInContext(source.slice(source.indexOf('async function saveBudget('),source.indexOf('function budgetBind(')),context);return{save:context.saveBudget,getPayload:()=>payload,getFilters:()=>filters}}
test('salva totais, mantém outros dados e filtra a versão lida',async()=>{const p=persistence(),b={id:'b',updated_at:'versao-anterior',dados:{legado:'preservar'}},d={base:100,etapas:[],historico:[]};await p.save(b,d,'Editou');assert.equal(p.getPayload().dados.legado,'preservar');assert.equal(p.getPayload().realizado,100);assert.deepEqual(p.getFilters(),[['id','b'],['updated_at','versao-anterior']]);assert.equal(p.getPayload().dados.mcl_orcamento.historico[0].acao,'Editou')});
test('conflito de edição não é tratado como sucesso',async()=>{const p=persistence({error:{code:'PGRST116'}});await assert.rejects(()=>p.save({id:'b'},{base:0,etapas:[],historico:[]},'Editou'),/outra pessoa/)});
test('usuário sem permissão não tenta gravar',async()=>{const p=persistence({administrator:false});await assert.rejects(()=>p.save({id:'b'},{},'Editou'),/administradores/);assert.equal(p.getPayload(),undefined)});
